name       : perl-scalar-list-utils
version    : '1.49'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.49.tar.gz : f4ffdd4833e872f472c22a86cd8057e715e565c247d94bd5f9b3ba9af284bfdc
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A selection of general-utility list subroutines
description: |
    A selection of general-utility list subroutines
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
