name       : perl-scalar-list-utils
version    : '1.63'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.63.tar.gz : cafbdf212f6827dc9a0dd3b57b6ee50e860586d7198228a33262d55c559eb2a9
homepage   : https://metacpan.org/dist/Scalar-List-Utils
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Scalar::Util, List::Util and Sub::Util perl modules
description: |
    This package contains a selection of subroutines that people have expressed would be nice to have in the perl core, but the usage would not really be high enough to warrant the use of a keyword, and the size so small such that being individual extensions would be wasteful.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
