name       : perl-scalar-list-utils
version    : '1.47'
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.47.tar.gz : c483347372a96972d61fd186522a9dafc2da899ef2951964513b7e8efb37efe1
license    : GPL-2.0
component  : programming.perl
summary    : A selection of general-utility list subroutines
description: |
    A selection of general-utility list subroutines
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
